/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Repuesto;
import javax.swing.*;
import java.awt.*;
import java.text.NumberFormat;
import java.util.*;

/**
 * Frame principal para clientes - Vista de repuestos con filtros y ordenamiento
 * Diseño: 1098x795 píxeles
 * @author Osvaldo
 */
public class Cliente extends javax.swing.JFrame {
    
    // Datos de ejemplo (en el futuro se conectará a un servicio real)
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnLimpiarFiltros;
    private javax.swing.JComboBox<String> cboCategoria;
    private javax.swing.JComboBox<String> cboOrdenamiento;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblOrden;
    private javax.swing.JLabel lblResultados;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuarioLogueado;
    private javax.swing.JPanel panelFiltros;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelRepuestos;
    private javax.swing.JScrollPane scrollRepuestos;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
    
    // Datos
    private java.util.List<Repuesto> repuestosOriginales;
    private java.util.List<Repuesto> repuestosFiltrados;
    
    // Categorías disponibles
    private final String[] CATEGORIAS = {
        "Todas las categorias",
        "Motor",
        "Transmision", 
        "Frenos",
        "Electrico",
        "Suspension",
        "Carroceria",
        "Lubricantes"
    };
    
    // Opciones de ordenamiento
    private final String[] ORDENAMIENTO = {
        "Nombre (A-Z)",
        "Nombre (Z-A)",
        "Precio (Menor a Mayor)",
        "Precio (Mayor a Menor)",
        "Stock (Menor a Mayor)",
        "Stock (Mayor a Menor)"
    };
    
    /**
     * Constructor principal
     */
    public Cliente() {
        initComponents();
        inicializarServicios();
        cargarUsuarioLogueado();
        cargarRepuestos();
        configurarEventos();
    }
    
    /**
     * Constructor con usuario específico
     */
    public Cliente(String nombreUsuario) {
        initComponents();
        inicializarServicios();
        establecerUsuarioLogueado(nombreUsuario);
        cargarRepuestos();
        configurarEventos();
    }
    
    /**
     * Inicializar datos necesarios
     */
    private void inicializarServicios() {
        repuestosOriginales = new ArrayList<>();
        repuestosFiltrados = new ArrayList<>();
    }
    
    /**
     * Cargar el nombre del usuario logueado desde SesionUsuarioActual
     */
    private void cargarUsuarioLogueado() {
        try {
            // Usar SesionUsuarioActual para obtener información de la sesión
            Percistencia.SesionUsuarioActual sesion = Percistencia.SesionUsuarioActual.getInstance();
            
            if (sesion.haySesionActiva()) {
                // Crear LoginService para obtener información completa del usuario
                Service.LoginService loginService = new Service.LoginService();
                String nombreCompleto = loginService.getNombreCompletoUsuarioActual();
                String rolUsuario = sesion.getRolUsuarioActual();
                
                establecerUsuarioLogueado(nombreCompleto + " (" + rolUsuario + ")");
            } else {
                establecerUsuarioLogueado("Cliente Demo");
            }
        } catch (Exception e) {
            // Si hay algún error, usar valor por defecto
            System.err.println("Error al cargar usuario logueado: " + e.getMessage());
            establecerUsuarioLogueado("Cliente Demo");
        }
    }
    
    /**
     * Establecer el nombre del usuario en el label
     */
    private void establecerUsuarioLogueado(String nombreUsuario) {
        if (nombreUsuario != null && !nombreUsuario.trim().isEmpty()) {
            lblUsuarioLogueado.setText("Usuario: " + nombreUsuario);
        } else {
            lblUsuarioLogueado.setText("👤 Usuario: No identificado");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblUsuarioLogueado = new javax.swing.JLabel();
        panelFiltros = new javax.swing.JPanel();
        lblBuscar = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        lblCategoria = new javax.swing.JLabel();
        cboCategoria = new javax.swing.JComboBox<>();
        lblOrden = new javax.swing.JLabel();
        cboOrdenamiento = new javax.swing.JComboBox<>();
        btnLimpiarFiltros = new javax.swing.JButton();
        lblResultados = new javax.swing.JLabel();
        scrollRepuestos = new javax.swing.JScrollPane();
        panelRepuestos = new javax.swing.JPanel();
        btnCerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JAO Workshop - Cliente - Catalogo de Repuestos");

        panelPrincipal.setBackground(new java.awt.Color(0, 0, 0));
        panelPrincipal.setPreferredSize(new java.awt.Dimension(980, 660));

        lblTitulo.setBackground(new java.awt.Color(0, 153, 0));
        lblTitulo.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 22)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("CATALOGO DE REPUESTOS - JAO WORKSHOP");
        lblTitulo.setOpaque(true);

        lblUsuarioLogueado.setFont(new java.awt.Font("JetBrains Mono", 1, 16)); // NOI18N
        lblUsuarioLogueado.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuarioLogueado.setText("Usuario: Cargando...");

        panelFiltros.setBackground(new java.awt.Color(0, 0, 0));
        panelFiltros.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)), "FILTROS Y BUSQUEDA", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("JetBrains Mono ExtraBold", 1, 14), new java.awt.Color(0, 153, 0))); // NOI18N

        lblBuscar.setFont(new java.awt.Font("JetBrains Mono", 1, 13)); // NOI18N
        lblBuscar.setForeground(new java.awt.Color(255, 255, 255));
        lblBuscar.setText("Buscar:");

        txtBuscar.setBackground(new java.awt.Color(255, 255, 255));
        txtBuscar.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        txtBuscar.setForeground(new java.awt.Color(0, 0, 0));

        lblCategoria.setFont(new java.awt.Font("JetBrains Mono", 1, 13)); // NOI18N
        lblCategoria.setForeground(new java.awt.Color(255, 255, 255));
        lblCategoria.setText("Categoria:");

        cboCategoria.setBackground(new java.awt.Color(255, 255, 255));
        cboCategoria.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        cboCategoria.setForeground(new java.awt.Color(0, 0, 0));
        cboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas las categorias", "Motor", "Transmision", "Frenos", "Electrico", "Suspension", "Carroceria", "Lubricantes" }));

        lblOrden.setFont(new java.awt.Font("JetBrains Mono", 1, 13)); // NOI18N
        lblOrden.setForeground(new java.awt.Color(255, 255, 255));
        lblOrden.setText("Ordenar:");

        cboOrdenamiento.setBackground(new java.awt.Color(255, 255, 255));
        cboOrdenamiento.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        cboOrdenamiento.setForeground(new java.awt.Color(0, 0, 0));
        cboOrdenamiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre (A-Z)", "Nombre (Z-A)", "Precio (Menor a Mayor)", "Precio (Mayor a Menor)", "Stock (Menor a Mayor)", "Stock (Mayor a Menor)" }));

        btnLimpiarFiltros.setBackground(new java.awt.Color(0, 153, 0));
        btnLimpiarFiltros.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 12)); // NOI18N
        btnLimpiarFiltros.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiarFiltros.setText("Limpiar");
        btnLimpiarFiltros.setBorder(null);
        btnLimpiarFiltros.setFocusPainted(false);

        lblResultados.setFont(new java.awt.Font("JetBrains Mono", 1, 13)); // NOI18N
        lblResultados.setForeground(new java.awt.Color(0, 153, 0));
        lblResultados.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblResultados.setText("0 repuestos");

        javax.swing.GroupLayout panelFiltrosLayout = new javax.swing.GroupLayout(panelFiltros);
        panelFiltros.setLayout(panelFiltrosLayout);
        panelFiltrosLayout.setHorizontalGroup(
            panelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFiltrosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(panelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFiltrosLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(cboOrdenamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFiltrosLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnLimpiarFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(lblResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(380, Short.MAX_VALUE))
        );
        panelFiltrosLayout.setVerticalGroup(
            panelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFiltrosLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(panelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cboOrdenamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnLimpiarFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        scrollRepuestos.setBackground(new java.awt.Color(0, 0, 0));
        scrollRepuestos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)), "REPUESTOS DISPONIBLES", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("JetBrains Mono ExtraBold", 1, 14), new java.awt.Color(0, 153, 0))); // NOI18N

        panelRepuestos.setBackground(new java.awt.Color(0, 0, 0));
        panelRepuestos.setLayout(new java.awt.GridBagLayout());
        scrollRepuestos.setViewportView(panelRepuestos);

        btnCerrarSesion.setBackground(new java.awt.Color(220, 53, 69));
        btnCerrarSesion.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 14)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setText("Cerrar Sesion");
        btnCerrarSesion.setFocusPainted(false);

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 1180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrollRepuestos, javax.swing.GroupLayout.PREFERRED_SIZE, 1180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuarioLogueado, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblUsuarioLogueado, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(panelFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(scrollRepuestos, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

    
    /**
     * Cargar repuestos - Actualmente usa datos de ejemplo
     * TODO: Implementar integración con base de datos o servicio de repuestos
     */
    private void cargarRepuestos() {
        repuestosOriginales.clear();
        
        // Por ahora, crear repuestos de ejemplo
        // En el futuro, esto se conectaría a un servicio de repuestos
        crearRepuestosDeEjemplo();
        
        aplicarFiltrosYMostrar();
    }
    
    /**
     * Crear repuestos de ejemplo para demostración
     */
    private void crearRepuestosDeEjemplo() {
        // MOTOR
        repuestosOriginales.add(new Repuesto(1, "Filtro de Aceite", "Filtro de aceite original para motor", "Bosch", "Motor", 25.50, 15));
        repuestosOriginales.add(new Repuesto(2, "Bujías NGK", "Juego de 4 bujías de platino", "NGK", "Motor", 45.99, 25));
        repuestosOriginales.add(new Repuesto(3, "Correa de Distribución", "Correa de distribución original", "Gates", "Motor", 89.50, 8));
        repuestosOriginales.add(new Repuesto(4, "Bomba de Agua", "Bomba de agua con junta", "Hepu", "Motor", 125.00, 6));
        
        // FRENOS
        repuestosOriginales.add(new Repuesto(5, "Pastillas de Freno", "Pastillas de freno cerámicas delanteras", "Brembo", "Frenos", 85.00, 8));
        repuestosOriginales.add(new Repuesto(6, "Discos de Freno", "Par de discos ventilados delanteros", "ATE", "Frenos", 155.75, 4));
        repuestosOriginales.add(new Repuesto(7, "Líquido de Frenos", "Líquido DOT 4 - 500ml", "Bosch", "Frenos", 18.99, 30));
        
        // SUSPENSIÓN
        repuestosOriginales.add(new Repuesto(8, "Amortiguador Trasero", "Amortiguador trasero para suspensión", "Monroe", "Suspensión", 120.75, 5));
        repuestosOriginales.add(new Repuesto(9, "Resorte Delantero", "Resorte espiral delantero", "Eibach", "Suspensión", 95.50, 7));
        repuestosOriginales.add(new Repuesto(10, "Rotula de Dirección", "Rotula de dirección izquierda", "TRW", "Suspensión", 65.25, 10));
        
        // ELÉCTRICO
        repuestosOriginales.add(new Repuesto(11, "Batería 12V", "Batería de 12V 60Ah para automóvil", "Varta", "Eléctrico", 95.00, 12));
        repuestosOriginales.add(new Repuesto(12, "Alternador", "Alternador 90A para sistema eléctrico", "Valeo", "Eléctrico", 180.50, 6));
        repuestosOriginales.add(new Repuesto(13, "Starter Motor", "Motor de arranque reconstruido", "Bosch", "Eléctrico", 220.00, 3));
        repuestosOriginales.add(new Repuesto(14, "Cables de Bujía", "Juego de cables de alta tensión", "NGK", "Eléctrico", 55.75, 18));
        
        // TRANSMISIÓN
        repuestosOriginales.add(new Repuesto(15, "Kit de Embrague", "Kit completo de embrague para transmisión manual", "LUK", "Transmisión", 450.00, 3));
        repuestosOriginales.add(new Repuesto(16, "Aceite de Transmisión", "Aceite ATF para transmisión automática", "Mobil 1", "Transmisión", 42.99, 14));
        repuestosOriginales.add(new Repuesto(17, "Filtro de Transmisión", "Filtro interno para caja automática", "Mann", "Transmisión", 38.50, 9));
        
        // CARROCERÍA
        repuestosOriginales.add(new Repuesto(18, "Parachoques Delantero", "Parachoques delantero original", "OEM", "Carrocería", 280.00, 2));
        repuestosOriginales.add(new Repuesto(19, "Faro Derecho", "Faro delantero derecho con regulación", "Hella", "Carrocería", 165.99, 4));
        repuestosOriginales.add(new Repuesto(20, "Espejo Retrovisor", "Espejo lateral izquierdo eléctrico", "TYC", "Carrocería", 89.75, 6));
        
        // LUBRICANTES
        repuestosOriginales.add(new Repuesto(21, "Aceite Motor 5W-30", "Aceite sintético para motor 4 litros", "Castrol", "Lubricantes", 35.99, 20));
        repuestosOriginales.add(new Repuesto(22, "Aceite Motor 15W-40", "Aceite mineral para motor diésel 5 litros", "Shell", "Lubricantes", 28.75, 25));
        repuestosOriginales.add(new Repuesto(23, "Grasa Multiuso", "Grasa de litio para rodamientos", "Mobil", "Lubricantes", 15.50, 35));
        repuestosOriginales.add(new Repuesto(24, "Refrigerante Motor", "Anticongelante concentrado 1 litro", "Prestone", "Lubricantes", 22.99, 40));
    }
    
    /**
     * Aplicar filtros y mostrar repuestos
     */
    private void aplicarFiltrosYMostrar() {
        // Limpiar lista filtrada
        repuestosFiltrados.clear();
        
        String busqueda = txtBuscar.getText().toLowerCase().trim();
        String categoriaSeleccionada = (String) cboCategoria.getSelectedItem();
        
        // Aplicar filtros
        for (Repuesto repuesto : repuestosOriginales) {
            boolean cumpleFiltros = true;
            
            // Filtro por búsqueda de nombre
            if (!busqueda.isEmpty() && !repuesto.getNombre().toLowerCase().contains(busqueda)) {
                cumpleFiltros = false;
            }
            
            // Filtro por categoría
            if (!categoriaSeleccionada.equals("Todas las categorias") && 
                !repuesto.getCategoria().equals(categoriaSeleccionada)) {
                cumpleFiltros = false;
            }
            
            if (cumpleFiltros) {
                repuestosFiltrados.add(repuesto);
            }
        }
        
        // Aplicar ordenamiento
        aplicarOrdenamiento();
        
        // Mostrar repuestos
        mostrarRepuestos();
        
        // Actualizar contador - Más compacto
        lblResultados.setText(repuestosFiltrados.size() + " repuestos");
    }
    
    /**
     * Aplicar ordenamiento a la lista filtrada
     */
    private void aplicarOrdenamiento() {
        String ordenSeleccionado = (String) cboOrdenamiento.getSelectedItem();
        
        switch (ordenSeleccionado) {
            case "Nombre (A-Z)":
                repuestosFiltrados.sort((r1, r2) -> r1.getNombre().compareToIgnoreCase(r2.getNombre()));
                break;
            case "Nombre (Z-A)":
                repuestosFiltrados.sort((r1, r2) -> r2.getNombre().compareToIgnoreCase(r1.getNombre()));
                break;
            case "Precio (Menor a Mayor)":
                repuestosFiltrados.sort((r1, r2) -> Double.compare(r1.getPrecio(), r2.getPrecio()));
                break;
            case "Precio (Mayor a Menor)":
                repuestosFiltrados.sort((r1, r2) -> Double.compare(r2.getPrecio(), r1.getPrecio()));
                break;
            case "Stock (Menor a Mayor)":
                repuestosFiltrados.sort((r1, r2) -> Integer.compare(r1.getStock(), r2.getStock()));
                break;
            case "Stock (Mayor a Menor)":
                repuestosFiltrados.sort((r1, r2) -> Integer.compare(r2.getStock(), r1.getStock()));
                break;
        }
    }
    
    /**
     * Mostrar repuestos en el panel con diseño de cards
     */
    private void mostrarRepuestos() {
        panelRepuestos.removeAll();
        
        if (repuestosFiltrados.isEmpty()) {
            // Mostrar mensaje cuando no hay resultados
            JLabel lblSinResultados = new JLabel("No se encontraron repuestos con los filtros aplicados");
            lblSinResultados.setFont(new Font("JetBrains Mono", Font.BOLD, 16));
            lblSinResultados.setForeground(new Color(200, 200, 200));
            
            GridBagConstraints gbc = new GridBagConstraints();
            gbc.gridx = 0;
            gbc.gridy = 0;
            gbc.insets = new Insets(50, 20, 50, 20);
            panelRepuestos.add(lblSinResultados, gbc);
        } else {
            // Configurar layout para cards en grid con scroll vertical
            GridBagConstraints gbc = new GridBagConstraints();
            gbc.insets = new Insets(8, 8, 8, 8);
            gbc.anchor = GridBagConstraints.NORTHWEST;
            
            int col = 0;
            int row = 0;
            int maxCols = 4; // 4 cards por fila para aprovechar el ancho
            
            for (Repuesto repuesto : repuestosFiltrados) {
                JPanel cardRepuesto = crearCardRepuesto(repuesto);
                
                gbc.gridx = col;
                gbc.gridy = row;
                gbc.weightx = 0.25; // Distribuir equitativamente el ancho
                gbc.weighty = 0.0;
                panelRepuestos.add(cardRepuesto, gbc);
                
                col++;
                if (col >= maxCols) {
                    col = 0;
                    row++;
                }
            }
            
            // Agregar componente invisible para permitir scroll vertical
            gbc.gridx = 0;
            gbc.gridy = row + 1;
            gbc.gridwidth = maxCols;
            gbc.weightx = 1.0;
            gbc.weighty = 1.0;
            gbc.fill = GridBagConstraints.BOTH;
            panelRepuestos.add(new JLabel(), gbc);
        }
        
        panelRepuestos.revalidate();
        panelRepuestos.repaint();
    }
    
    /**
     * Crear una card estética para mostrar un repuesto - Optimizada para pantalla más pequeña
     */
    private JPanel crearCardRepuesto(Repuesto repuesto) {
        JPanel card = new JPanel();
        card.setLayout(null);
        card.setPreferredSize(new Dimension(230, 170)); // Ajustado para 980px
        card.setBackground(new Color(0, 0, 0)); // Fondo negro Kawasaki
        card.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(new Color(0, 153, 0), 2),
            BorderFactory.createEmptyBorder(8, 8, 8, 8)
        ));
        
        // Nombre del repuesto - Más compacto
        JLabel lblNombre = new JLabel(repuesto.getNombre());
        lblNombre.setBounds(6, 6, 215, 20); // Ajustado para 230px
        lblNombre.setFont(new Font("JetBrains Mono ExtraBold", Font.BOLD, 13));
        lblNombre.setForeground(new Color(255, 255, 255)); // Texto blanco
        card.add(lblNombre);
        
        // Categoría con color
        JLabel lblCategoria = new JLabel(repuesto.getCategoria());
        lblCategoria.setBounds(6, 26, 120, 16); // Ajustado
        lblCategoria.setFont(new Font("JetBrains Mono ExtraBold", Font.PLAIN, 10));
        lblCategoria.setForeground(new Color(0, 153, 0));
        card.add(lblCategoria);
        
        // Marca
        JLabel lblMarca = new JLabel("Marca: " + repuesto.getMarca());
        lblMarca.setBounds(130, 26, 95, 16); // Ajustado para 230px
        lblMarca.setFont(new Font("JetBrains Mono", Font.PLAIN, 11));
        lblMarca.setForeground(new Color(200, 200, 200)); // Gris claro
        card.add(lblMarca);
        
        // Descripción - Más compacta
        JTextArea txtDescripcion = new JTextArea(repuesto.getDescripcion());
        txtDescripcion.setBounds(6, 46, 215, 30); // Ajustado para 230px
        txtDescripcion.setFont(new Font("JetBrains Mono", Font.PLAIN, 10));
        txtDescripcion.setForeground(new Color(180, 180, 180)); // Gris más claro
        txtDescripcion.setBackground(new Color(0, 0, 0)); // Fondo negro
        txtDescripcion.setEditable(false);
        txtDescripcion.setLineWrap(true);
        txtDescripcion.setWrapStyleWord(true);
        txtDescripcion.setBorder(null); // Sin borde
        card.add(txtDescripcion);
        
        // Precio
        NumberFormat formatoPrecio = NumberFormat.getCurrencyInstance();
        JLabel lblPrecio = new JLabel("Precio: " + formatoPrecio.format(repuesto.getPrecio()));
        lblPrecio.setBounds(6, 82, 120, 22); // Ajustado
        lblPrecio.setFont(new Font("JetBrains Mono ExtraBold", Font.BOLD, 14));
        lblPrecio.setForeground(new Color(0, 153, 0));
        card.add(lblPrecio);
        
        // Stock
        JLabel lblStock = new JLabel("Stock: " + repuesto.getStock() + " unidades");
        lblStock.setBounds(6, 108, 160, 16); // Ajustado
        lblStock.setFont(new Font("JetBrains Mono", Font.PLAIN, 11));
        Color colorStock = repuesto.getStock() > 10 ? new Color(40, 167, 69) : 
                          repuesto.getStock() > 5 ? new Color(255, 193, 7) : new Color(220, 53, 69);
        lblStock.setForeground(colorStock);
        card.add(lblStock);
        
        // ID del repuesto
        JLabel lblId = new JLabel("ID: " + repuesto.getIdRepuesto());
        lblId.setBounds(170, 108, 55, 16); // Ajustado para 230px
        lblId.setFont(new Font("JetBrains Mono", Font.PLAIN, 10));
        lblId.setForeground(new Color(150, 150, 150)); // Gris medio
        card.add(lblId);
        
        // Disponibilidad
        JLabel lblDisponible = new JLabel(repuesto.getStock() > 0 ? "DISPONIBLE" : "AGOTADO");
        lblDisponible.setBounds(6, 128, 100, 16);
        lblDisponible.setFont(new Font("JetBrains Mono ExtraBold", Font.BOLD, 9));
        lblDisponible.setForeground(repuesto.getStock() > 0 ? new Color(0, 153, 0) : new Color(220, 53, 69));
        card.add(lblDisponible);
        
        // Efectos hover con colores Kawasaki
        card.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                card.setBorder(BorderFactory.createCompoundBorder(
                    BorderFactory.createLineBorder(new Color(0, 200, 0), 3), // Verde más brillante en hover
                    BorderFactory.createEmptyBorder(13, 13, 13, 13)
                ));
                card.setBackground(new Color(20, 20, 20)); // Negro más claro en hover
            }
            
            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                card.setBorder(BorderFactory.createCompoundBorder(
                    BorderFactory.createLineBorder(new Color(0, 153, 0), 2),
                    BorderFactory.createEmptyBorder(8, 8, 8, 8)
                ));
                card.setBackground(new Color(0, 0, 0)); // Volver al negro original
            }
        });
        
        return card;
    }
    

    

    
    /**
     * Configurar eventos de los componentes
     */
    private void configurarEventos() {
        // Evento de búsqueda en tiempo real
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyReleased(java.awt.event.KeyEvent evt) {
                aplicarFiltrosYMostrar();
            }
        });
        
        // Evento de cambio de categoría
        cboCategoria.addActionListener(e -> aplicarFiltrosYMostrar());
        
        // Evento de cambio de ordenamiento
        cboOrdenamiento.addActionListener(e -> aplicarFiltrosYMostrar());
        
        // Evento limpiar filtros
        btnLimpiarFiltros.addActionListener(e -> {
            txtBuscar.setText("");
            cboCategoria.setSelectedIndex(0);
            cboOrdenamiento.setSelectedIndex(0);
            aplicarFiltrosYMostrar();
        });
        
        // Evento cerrar sesión
        btnCerrarSesion.addActionListener(e -> {
            int confirmacion = JOptionPane.showConfirmDialog(
                this,
                "¿Está seguro que desea cerrar la sesión?",
                "Confirmar Cierre de Sesión",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
            );
            
            if (confirmacion == JOptionPane.YES_OPTION) {
                this.dispose();
                // Aquí puedes abrir la ventana de login si es necesario
                // new Login().setVisible(true);
            }
        });
    }
    
    /**
     * Método main para testing
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Cliente().setVisible(true);
        });
    }
}